name: Build and publish

on:
  workflow_dispatch:

permissions:
  packages: write

jobs:
  release:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dagger/dagger-for-github@8.0.0
        name: build-and-publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          call: build-and-publish --gh-user ${{ github.actor }} --gh-auth-token env://GH_TOKEN
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "latest"
